name: google_maps_places_picker
description: A refractored version of the Google Maps Places Picker plugin for Flutter.
version: 0.0.2
homepage: https://github.com/varunhhhrahul/google_maps_places_picker_refractored

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.0
  # permission_handler: ^9.2.0
  provider: ^6.0.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  tuple: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: 
 